site_name: FastAPI Beyond CRUD
nav:
  - Home: index.md
  - Project: 
      - Installation and Project SetUp: chapter1.md
      - Creating a Simple Web Server: chapter2.md
      - Building a CRUD REST API: chapter3.md 
      - Large Project Structure Using Routers: chapter4.md
      - Databases with SQLModel: chapter5.md
      - Finishing Up the CRUD: chapter6.md
      - Creating a user authentication model: chapter7.md
      - User Account Creation: chapter8.md

theme: 
 name: material
 palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jod35



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition


repo_name: jod35/fastapi-beyond-CRUD
repo_url: https://github.com/jod35/fastapi-beyond-CRUD